[project]
name = "smart-learning-python-ai"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic-settings",
    "sqlalchemy",
    "alembic",
    "psycopg[binary]",
    "pgvector",
]

[project.optional-dependencies]
dev = [
    "pytest",
]