"""create knowledge base

Revision ID: 8db4f95f78d4
Revises: 
Create Date: 2026-08-09 11:39:35.691092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
# revision identifiers, used by Alembic.
revision: str = '8db4f95f78d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_locator', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    schema='ai_engine'
    )
    op.create_index(op.f('ix_document_chunks_course_id'), 'document_chunks', ['course_id'], unique=False, schema='ai_engine')
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False, schema='ai_engine')
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('model_key', sa.String(length=200), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['ai_engine.document_chunks.id'], name=op.f('fk_chunk_embeddings_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'chunk_id', name=op.f('pk_chunk_embeddings')),
    schema='ai_engine'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_embeddings', schema='ai_engine')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks', schema='ai_engine')
    op.drop_index(op.f('ix_document_chunks_course_id'), table_name='document_chunks', schema='ai_engine')
    op.drop_table('document_chunks', schema='ai_engine')
    # ### end Alembic commands ###
