import DocumentViewer from './DocumentViewer.vue'

export { default as BaseAlert } from './BaseAlert.vue'
export { default as BaseBadge } from './BaseBadge.vue'
export { default as BaseButton } from './BaseButton.vue'
export { default as BaseCard } from './BaseCard.vue'
export { default as BaseEmptyState } from './BaseEmptyState.vue'
export { default as BaseInput } from './BaseInput.vue'
export { default as BasePageHeader } from './BasePageHeader.vue'
export { default as BasePagination } from './BasePagination.vue'
export { default as BaseStatCard } from './BaseStatCard.vue'
export { default as BaseTabs } from './BaseTabs.vue'
export {default as DocumentViewer} from './DocumentViewer.vue'
export type { TabItem } from './BaseTabs.vue'